apiVersion: v1
kind: Service
metadata:
  name: kafka-broker-nodeport
spec:
  type: NodePort
  selector:
    app: kafka-kafka-0 # This should match the labels of your deployment pods
  ports:
    - protocol: TCP
      port: 9092 # Port the service listens on
      targetPort: 9092 # Target port of the pod