apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: topic
  labels:
    strimzi.io/cluster: kafka  # The name of your Kafka cluster
  namespace: default  # The namespace where your Kafka cluster is deployed
spec:
  partitions: 3  # Number of partitions
  replicas: 1  # Number of replicas
  config:
    retention.ms: 7200000  # Message retention time in milliseconds
    segment.bytes: 1073741824  # The size of a single log file
