apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: trytopic
  namespace: kafka
  labels:
    strimzi.io/cluster: my-kafka-cluster-kafka-0
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: 604800000
    segment.bytes: 1073741824
