apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafkascriptv2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafkascriptv2
  template:
    metadata:
      labels:
        app: kafkascriptv2
    spec:
      containers:
      - name: kafkascriptv2
        image: stekinho/kafkascriptv2:v7
      #restartPolicy: Never
